### ISSUE TITLE
NoSirveLaSRC

### ISSUE THREAD

**Issue by ValoriomMX** [m3xicang0d/MexicanHubcore#1]
No sirve esta porquería de hubcore

**Comment by m3xicang0d** [comment]
the code works completely, it is not made for people who do not know how to use maven. haha greetings!

**Comment by ValoriomMX** [comment]
> the code works completely, it is not made for people who do not know how to use maven. haha greetings!

no hablo taka taka soy developer de lunar.gg minehq.com y cheatbreaker.com como me dices que no tengo idea como usar maven
